use mysql; 
update user set password=PASSWORD("123456") where user="root";
FLUSH PRIVILEGES;
grant all privileges on *.* to 'root'@'%' identified by '123456' with grant option;
GRANT ALL PRIVILEGES ON *.* TO ' root,'@'172.16.62.172' IDENTIFIED BY '123456';
FLUSH PRIVILEGES;
grant all privileges on *.* to 'root'@'%' identified by 'root' with grant option;
GRANT ALL PRIVILEGES ON *.* TO ' root,'@'172.16.62.172' IDENTIFIED BY 'root';
use mysql; 
update user set password=PASSWORD("root") where user="root";
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO ' root,'@'172.16.62.25' IDENTIFIED BY 'root';
FLUSH PRIVILEGES;
